import { PrismaClient } from '@prisma/client';
import { NextApiRequest, NextApiResponse } from 'next';

const handler = async (req: NextApiRequest, res: NextApiResponse) => {
	const prisma = new PrismaClient();

	// delete every item in database "reset"
    await prisma.production.deleteMany();
	await prisma.type.deleteMany();
	await prisma.genre.deleteMany();
	//

	await prisma.type.createMany({
		data: [{ name: 'MOVIE' }, { name: 'SERIE' }],
	});

	await prisma.genre.createMany({
		data: [
            {name: 'NEW'},
			{ name: 'ACTION' },
			{ name: 'ADVENTURE' },
			{ name: 'ANIME' },
			{ name: 'COMEDY' },
			{ name: 'CRIME' },
			{ name: 'FAMILY' },
			{ name: 'HORROR' },
		],
	});

    
    // types ids
	const types = await prisma.type.findMany();
    const movieTypeId = types.find(type => type.name === 'MOVIE')?.id || '1';
    const serieTypeId = types.find(type => type.name === 'SERIE')?.id || '1';
    //

    // genres ids
	const genres = await prisma.genre.findMany();
    const actionGenreId = genres.find(genre => genre.name === 'ACTION')?.id || '1';
    const animeGenreId = genres.find(genre => genre.name === 'ANIME')?.id || '1';
    const adventureGenreId = genres.find(genre => genre.name === 'ADVENTURE')?.id || '1';
    const comedyGenreId = genres.find(genre => genre.name === 'COMEDY')?.id || '1';
    const crimeGenreId = genres.find(genre => genre.name === 'CRIME')?.id || '1';
    const horrorGenreId = genres.find(genre => genre.name === 'HORROR')?.id || '1';
    const familyGenreId = genres.find(genre => genre.name === 'FAMILY')?.id || '1';
    const newGenreId = genres.find(genre => genre.name === 'NEW')?.id || '1'
    //

   await prisma.production.createMany({
    data: [
        {
        title: 'One Piece',
        description: 'Calling themselves the Straw Hats, Luffy and his gang sail from island to island in search of the mysterious One Piece treasure. Of course, no adventure is smooth sailing. On their quest, the Straw Hats run into dangerous rivals who stand in their way of hitting the jackpot.',
        slug: 'one-piece',
        image: 'https://cdn.i-scmp.com/sites/default/files/d8/images/canvas/2023/01/31/ce9f52f2-5bd4-49ca-9d71-28bc2e32878b_351db1ba.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=Ades3pQbeh8',
        created_by : 'Eiichirō Oda, Steven Maeda',
        year_of_publication: '2023',
        length : '1 season : 8 episodes',
        allowed_age: '13+',
        genreId : newGenreId,
        genre_name : 'NEW',
        typeId:serieTypeId,
    
    }, 

    {
        title: 'Death Note',
        description: 'The story follows Light Yagami, a genius high school student who discovers a mysterious notebook: the "Death Note", which belonged to the shinigami Ryuk, and grants the user the supernatural ability to kill anyone whose name is written in its pages.',
        slug: 'death-note',
        image: 'https://i.ebayimg.com/images/g/sdUAAOSwndxgdD0h/s-l1200.webp',
        youtubeURL: 'https://www.youtube.com/watch?v=NlJZ-YgAt-c',
        created_by : 'Tsugumi Ōba',
        year_of_publication: '2006',
        length : '1 season : 37 episodes',
        allowed_age: '13+',
        genre_name: 'ANIME',
        genreId : animeGenreId,
        typeId:serieTypeId
    }, 
    {
        title: 'Inception',
        description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.',
        slug: 'inception',
        image: 'https://m.media-amazon.com/images/M/MV5BMjExMjkwNTQ0Nl5BMl5BanBnXkFtZTcwNTY0OTk1Mw@@._V1_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=YoHD9XEInc0',
        created_by: 'Christopher Nolan',
        year_of_publication: '2010',
        length: '2 hours : 28 minutes',
        allowed_age: '13+',
        genre_name: 'ACTION',
        genreId: actionGenreId,
        typeId: movieTypeId
    },
    {
        title: 'Breaking Bad',
        description: 'A high school chemistry teacher turned methamphetamine manufacturing drug dealer teams up with a former student.',
        slug: 'breaking-bad',
        image: 'https://m.media-amazon.com/images/M/MV5BYmQ4YWMxYjUtNjZmYi00MDQ1LWFjMjMtNjA5ZDdiYjdiODU5XkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=HhesaQXLuRY',
        created_by: 'Vince Gilligan',
        year_of_publication: '2008',
        length: '5 seasons : 62 episodes',
        allowed_age: '18+',
        genre_name:'CRIME',
        genreId: crimeGenreId,
        typeId: serieTypeId
    },
    {
        title: 'The Dark Knight',
        description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        slug: 'the-dark-knight',
        image: 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
        created_by: 'Christopher Nolan',
        year_of_publication: '2008',
        length: '2 hours : 32 minutes',
        allowed_age: '13+',
        genre_name: 'ACTION',
        genreId: actionGenreId,
        typeId: movieTypeId
    },
    {
        title: 'Game of Thrones',
        description: 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.',
        slug: 'game-of-thrones',
        image: 'https://m.media-amazon.com/images/M/MV5BN2IzYzBiOTQtNGZmMi00NDI5LTgxMzMtN2EzZjA1NjhlOGMxXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=KPLWWIOCOOQ',
        created_by: 'David Benioff, D.B. Weiss',
        year_of_publication: '2011',
        length: '8 seasons : 73 episodes',
        allowed_age: '18+',
        genre_name: 'ADVENTURE',
        genreId: adventureGenreId,
        typeId: serieTypeId
    },
    {
        title: 'Interstellar',
        description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
        slug: 'interstellar',
        image: 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
        created_by: 'Christopher Nolan',
        year_of_publication: '2014',
        length: '2 hours : 49 minutes',
        allowed_age: '13+',
        genre_name: 'ADVENTURE',
        genreId: adventureGenreId,
        typeId: movieTypeId
    },
    {
        title: 'The Matrix',
        description: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
        slug: 'the-matrix',
        image: 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=vKQi3bBA1y8',
        created_by: 'The Wachowskis',
        year_of_publication: '1999',
        length: '2 hours : 16 minutes',
        allowed_age: '16+',
        genre_name: 'ACTION',
        genreId: actionGenreId,
        typeId: movieTypeId
    },
    {
        title: 'Pulp Fiction',
        description: 'The lives of two mob hitmen, a boxer, a gangster\'s wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
        slug: 'pulp-fiction',
        image: 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=s7EdQ4FqbhY',
        created_by: 'Quentin Tarantino',
        year_of_publication: '1994',
        length: '2 hours 34 minutes',
        allowed_age: '18+',
        genre_name: 'CRIME',
        genreId: crimeGenreId,
        typeId: movieTypeId
    },
    {
        title: 'Cyberpunk: Edgerunners',
        description: 'Cyberpunk: Edgerunners tells a standalone, 10-episode story about a street kid trying to survive in a technology and body modification-obsessed city of the future. Having everything to lose, he chooses to stay alive by becoming an edgerunner—a mercenary outlaw also known as a cyberpunk.',
        slug: 'cyberpunk-edgerunners',
        image: 'https://m.media-amazon.com/images/M/MV5BMTQ0MGI4NTgtZTlkNy00YTU5LThjM2ItNDczMGFlZWY2ZWM3XkEyXkFqcGdeQXVyMTM3NDc1OTM2._V1_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=JtqIas3bYhg',
        created_by: 'Mike Pondsmith',
        year_of_publication: '2022',
        length: '1 season : 10 episodes',
        allowed_age: '18+',
        genre_name: 'ANIME',
        genreId: animeGenreId,
        typeId: serieTypeId
    },
    {
        title: 'The Devil on Trial',
        description: 'Logline. The Devil on Trial explores the first — and only — time “demonic possession” has officially been used as a defense in a US murder trial. Including firsthand accounts of alleged devil possession and a shocking murder, this extraordinary story forces reflection on our fear of the unknown.',
        slug: 'devil-on-trial',
        image: 'https://m.media-amazon.com/images/M/MV5BYmRjYTcwYTUtYWFmMy00NWM0LThiNjItN2JlZjZiODRkZTMyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UY1200_CR90,0,630,1200_AL_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=7YPoyoCR9K4',
        created_by: 'Arne Cheyenne Johnson',
        year_of_publication: '2023',
        length: '1 hour : 21 minutes',
        allowed_age: '18+',
        genre_name: 'NEW',
        genreId: newGenreId,
        typeId: movieTypeId
    },
    {
        title: 'The Godfather',
        description: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
        slug: 'the-godfather',
        image: 'https://m.media-amazon.com/images/M/MV5BYTBjZjY0MzItZWRiOC00ZDJmLTgyNGUtMzU5NTlkMzczODIxL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTMxMjgxMzA@._V1_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=UaVTIH8mujA',
        created_by: 'Francis Ford Coppola',
        year_of_publication: '1972',
        length: '2 hours : 55 minutes',
        allowed_age: '18+',
        genre_name: 'CRIME',
        genreId: crimeGenreId,
        typeId: movieTypeId
    },
    {
        title: 'The Lord of the Rings: The Fellowship of the Ring',
        description: 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.',
        slug: 'the-lord-of-the-rings-the-fellowship-of-the-ring',
        image: 'https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=V75dMMIW2B4',
        created_by: 'Peter Jackson',
        year_of_publication: '2001',
        length: '2 hours : 58 minutes',
        allowed_age: '12+',
        genre_name: 'ADVENTURE',
        genreId: adventureGenreId,
        typeId: movieTypeId
    },
    {
        title: 'The Dark Knight Rises',
        description: 'Eight years after the Joker\'s reign of anarchy, the Dark Knight, with the help of the enigmatic Selina, is forced from his exile to save Gotham City from the brutal guerrilla terrorist Bane.',
        slug: 'the-dark-knight-rises',
        image: 'https://m.media-amazon.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=g8evyE9TuYk',
        created_by: 'Christopher Nolan',
        year_of_publication: '2012',
        length: '2 hours : 44 minutes',
        allowed_age: '13+',
        genre_name: 'ACTION',
        genreId: actionGenreId,
        typeId: movieTypeId
    },
    {
        title: 'The Shawshank Redemption',
        description: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
        slug: 'the-shawshank-redemption',
        image: 'https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=NmzuHjWmXOc',
        created_by: 'Frank Darabont',
        year_of_publication: '1994',
        length: '2 hours : 22 minutes',
        allowed_age: '13+',
        genre_name: 'CRIME',
        genreId:crimeGenreId,
        typeId: movieTypeId
    },
    {
        title: 'Pride and Prejudice',
        description: 'A woman of fortune must receive the proposal of marriage from the very man who had previously insulted her.',
        slug: 'pride-and-prejudice',
        image: 'https://m.media-amazon.com/images/M/MV5BMTA1NDQ3NTcyOTNeQTJeQWpwZ15BbWU3MDA0MzA4MzE@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=Ur_DIHs92NM',
        created_by: 'Joe Wright',
        year_of_publication: '2005',
        length: '2 hours : 28 minutes',
        allowed_age: '12+',
        genre_name: 'FAMILY',
        genreId: familyGenreId,
        typeId: movieTypeId
    },
    {
        title: 'Hidden Strike',
        description: "What happens in Hidden Strike? When a group of international rebels target a massive oil refinery in Iraq, a private Chinese security team led by Commander Luo (Chan) volunteers to escort nearly 500 civilians to safety in Iraq's Green Zone.",
        slug: 'hidden-strike',
        image: 'https://m.media-amazon.com/images/M/MV5BYzM0YjcwM2QtN2FmMC00YjU2LWI3YzctNDZhOTJiN2VhYjQxXkEyXkFqcGdeQXVyMTU0NjA4Njk3._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=Kut3nPN04U4',
        created_by: 'Scott Waugh',
        year_of_publication: '2023',
        length: '2 hours : 10 minutes',
        allowed_age: '13+',
        genre_name: 'NEW',
        genreId: newGenreId,
        typeId: movieTypeId
    },
    {
        title: 'Attack on Titan',
        description: 'The story is set in a world where humanity lives inside cities and walls that surround a giant forest. The forest is inhabited by creatures referred to as Titans, who devour humans for sustenance.',
        slug: 'attack-on-titan',
        image: 'https://m.media-amazon.com/images/M/MV5BNDFjYTIxMjctYTQ2ZC00OGQ4LWE3OGYtNDdiMzNiNDZlMDAwXkEyXkFqcGdeQXVyNzI3NjY3NjQ@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=8pEg8NrdL_Y',
        created_by : 'Hajime Isayama',
        year_of_publication: '2009',
        length : '3 seasons : 39 episodes',
        allowed_age: '16+',
        genre_name: 'ANIME',
        genreId: animeGenreId,
        typeId: serieTypeId
      },
    {
        title: 'Jujutsu Kaisen',
        description: "Jujutsu Kaisen follows the story of Yuji Itadori, an ordinary boy who crosses paths with Megumi Fushiguro, a Jujutsu Sorcerer searching for a powerful Cursed Object known as Ryomen Sukuna's finger. Unintentionally, Yuji's friends unseal the Cursed Object, attracting dangerous Curses to their location.",
        slug: 'jujutsu-kaisen',
        image: 'https://m.media-amazon.com/images/M/MV5BMTMwMDM4N2EtOTJiYy00OTQ0LThlZDYtYWUwOWFlY2IxZGVjXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=pkKu9hLT-t8',
        created_by : 'Gege Akutami',
        year_of_publication: '2018',
        length : '1 seasons : 24 episodes',
        allowed_age: '13+',
        genre_name: 'ANIME',
        genreId: animeGenreId,
        typeId: serieTypeId
      },
      {
        title: 'Kimetsu no Yaiba',
        description: "It follows teenage Tanjiro Kamado, who strives to become a Demon Slayer after his family was slaughtered and his younger sister, Nezuko, is turned into a demon. A 26-episode anime television series adaptation produced by Ufotable aired from April to September 2019.",
        slug: 'kimetsu-no-yaiba',
        image: 'https://m.media-amazon.com/images/M/MV5BODI2NjdlYWItMTE1ZC00YzI2LTlhZGQtNzE3NzA4MWM0ODYzXkEyXkFqcGdeQXVyNjU1OTg4OTM@._V1_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=VQGCKyvzIM4',
        created_by : 'Koyoharu Gotōge,',
        year_of_publication: '2019',
        length : '2 seasons : 26 episodes',
        allowed_age: '13+',
        genre_name: 'ANIME',
        genreId: animeGenreId,
        typeId: serieTypeId
      },
      {
        title: 'The Big Bang Theory',
        description: 'The Big Bang Theory is an American sitcom created by Chuck Lorre and Lee Aronsohn that originally aired on CBS from September 24, 2007, to February 16, 2019.',
        slug: 'the-big-bang-theory',
        image: 'https://m.media-amazon.com/images/M/MV5BY2FmZTY5YTktOWRlYy00NmIyLWE0ZmQtZDg2YjlmMzczZDZiXkEyXkFqcGdeQXVyNjg4NzAyOTA@._V1_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=WBb3fojgW0Q',
        created_by: 'Chuck Lorre',
        year_of_publication: '2007',
        length: '8 seasons : 279 episodes',
        allowed_age: '13+',
        genre_name: 'COMEDY',
        genreId: comedyGenreId,
        typeId: serieTypeId
    },
    {
        title: 'Friends',
        description: 'Friends is an American sitcom created by David Crane and Marta Kauffman, which originally aired on NBC from September 22, 1994, to May 6, 2004.',
        slug: 'friends',
        image: 'https://m.media-amazon.com/images/M/MV5BNDVkYjU0MzctMWRmZi00NTkxLTgwZWEtOWVhYjZlYjllYmU4XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=LTpmw0Ac6Zs',
        created_by: 'David Crane, Marta Kauffman',
        year_of_publication: '1994',
        length: '10 seasons : 236 episodes',
        allowed_age: '13+',
        genre_name: 'COMEDY',
        genreId: comedyGenreId,
        typeId: serieTypeId
    },
    {
        title: 'The Simpsons',
        description: 'The Simpsons is an American animated sitcom created by Matt Groening for the Fox Broadcasting Company.',
        slug: 'the-simpsons',
        image: 'https://m.media-amazon.com/images/M/MV5BYjFkMTlkYWUtZWFhNy00M2FmLThiOTYtYTRiYjVlZWYxNmJkXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=3R1ebDCv7vM',
        created_by: 'Matt Groening',
        year_of_publication: '1989',
        length: '32 seasons : 691 episodes',
        allowed_age: '13+',
        genre_name: 'COMEDY',
        genreId: comedyGenreId,
        typeId: serieTypeId
    },
    {
        title: '30 Rock',
        description: '30 Rock is an American television comedy series created by Tina Fey and Robert Carlock that aired on NBC from October 11, 2006, to January 31, 2013.',
        slug: '30-rock',
        image: 'https://m.media-amazon.com/images/M/MV5BMjA5MDk5MTc4MV5BMl5BanBnXkFtZTcwODU3NTg1MQ@@._V1_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=6Og5GNktfkc',
        created_by: 'Tina Fey, Robert Carlock',
        year_of_publication: '2006',
        length: '7 seasons : 158 episodes',
        allowed_age: '13+',
        genre_name: 'COMEDY',
        genreId: comedyGenreId,
        typeId: serieTypeId
    },
    {
        title: 'Parks and Recreation',
        description: 'Parks and Recreation is an American television sitcom created by Greg Daniels and Michael Schur that originally aired on NBC from April 9, 2009, to February 22, 2015.',
        slug: 'parks-and-recreation',
        image: 'https://m.media-amazon.com/images/M/MV5BYWNkOTg0OTMtZTcyNy00MWU1LWJhZDQtYjQzMjU1NjBhYzI2XkEyXkFqcGdeQXVyOTE4NzcwNzI@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=5IZWeAwdJ-s',
        created_by: 'Greg Daniels, Michael Schur',
        year_of_publication: '2009',
        length: '7 seasons : 122 episodes',
        allowed_age: '13+',
        genre_name: 'COMEDY',
        genreId: comedyGenreId,
        typeId: serieTypeId
    },
    {
        title: 'Hunt for the Wilderpeople',
        description: 'A sullen teenage orphan goes on the lam with his survivalist foster uncle when child services comes for him.',
        slug: 'hunt-for-the-wilderpeople',
        image: 'https://m.media-amazon.com/images/M/MV5BMjI1MDQ2MDg5Ml5BMl5BanBnXkFtZTgwMjc2NjM5ODE@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=dPaU4Gymt3E',
        created_by: 'Taika Waititi',
        year_of_publication: '2016',
        length: '1 hour : 50 minutes',
        allowed_age: '13+',
        genre_name: 'COMEDY',
        genreId: comedyGenreId,
        typeId: movieTypeId
    },
    {
        title: 'This Is 40',
        description: 'A funny, heartfelt movie about the compromises of marriage and getting older.',
        slug: 'this-is-40',
        image: 'https://m.media-amazon.com/images/M/MV5BNzQxMDQ1NjA4N15BMl5BanBnXkFtZTcwNTE5MjQ3OA@@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=gxkNuHrS6cg',
        created_by: 'Judd Apatow',
        year_of_publication: '2012',
        length: '1 hour : 50 minutes',
        allowed_age: '13+',
        genre_name: 'COMEDY',
        genreId: comedyGenreId,
        typeId: movieTypeId
    },
    {
        title: 'Superbad',
        description: 'Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-soaked party goes awry.',
        slug: 'superbad',
        image: 'https://m.media-amazon.com/images/M/MV5BY2VkMDg4ZTYtN2M3Yy00NWZiLWE2ODEtZjU5MjZkYWNkNGIzXkEyXkFqcGdeQXVyODY5Njk4Njc@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=4eaZ_48ZYog',
        created_by: 'Greg Mottola',
        year_of_publication: '2007',
        length: '1 hour : 40 minutes',
        allowed_age: '17+',
        genre_name: 'COMEDY',
        genreId: comedyGenreId,
        typeId: movieTypeId
    },
    {
        title: 'The Hangover',
        description: 'Three buddies wake up in Las Vegas, with no memory of the previous night and the missing wedding groom.',
        slug: 'the-hangover',
        image: 'https://m.media-amazon.com/images/M/MV5BNGQwZjg5YmYtY2VkNC00NzliLTljYTctNzI5NmU3MjE2ODQzXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=tcdUhdOlz9M',
        created_by: 'Todd Phillips',
        year_of_publication: '2009',
        length: '1 hour : 45 minutes',
        allowed_age: '18+',
        genre_name: 'COMEDY',
        genreId: comedyGenreId,
        typeId: movieTypeId
    },
    {
        title: 'Dazed and Confused',
        description: 'The adventures of high school and junior high students on the last day of school in May 1976.',
        slug: 'dazed-and-confused',
        image: 'https://m.media-amazon.com/images/M/MV5BNDAwMWI4MTEtYWQxNS00Y2Q0LWJkZTktOWZhYzNiYzMwMDY3XkEyXkFqcGdeQXVyMTI0NTA1MDI3._V1_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=3aQuvPlcB-8',
        created_by: 'Richard Linklater',
        year_of_publication: '1993',
        length: '1 hour : 42 minutes',
        allowed_age: '18+',
        genre_name: 'COMEDY',
        genreId: comedyGenreId,
        typeId: movieTypeId
    },
    {
        title: 'Spirited Away',
        description: 'A young girl, Chihiro Ogino, goes to a bathhouse with her parents and ends up in the world of the gods.',
        slug: 'spirited-away',
        image: 'https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=ByXuk9QqQkk',
        created_by: 'Hayao Miyazaki',
        year_of_publication: '2001',
        length: '1 hour : 31 minutes',
        allowed_age: '13+',
        genre_name: 'ANIME',
        genreId: animeGenreId,
        typeId: movieTypeId
    },
    {
        title: 'Ponyo',
        description: 'A young fish girl falls in love with a five-year-old boy and transforms herself into a human girl to be with him.',
        slug: 'ponyo',
        image: 'https://m.media-amazon.com/images/M/MV5BZTY4MWUyZDMtNGVkZS00M2Q2LTliMTAtYmQzNTMyMzJlZTNmXkEyXkFqcGdeQXVyMjI5MjYyMjg@._V1_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=CsR3KVgBzSM',
        created_by: 'Hayao Miyazaki',
        year_of_publication: '2008',
        length: '1 hour : 33 minutes',
        allowed_age: '13+',
        genre_name: 'ANIME',
        genreId: animeGenreId,
        typeId: movieTypeId
    },
    {
        title: 'Castle in the Sky',
        description: 'A young boy and a girl with a mysterious crystal find a legendary floating castle which is said to grant wishes.',
        slug: 'castle-in-the-sky',
        image: 'https://m.media-amazon.com/images/M/MV5BNDFhZmY2NTgtMzljYy00MTlhLTgyMjItNTEwZWJkYThhYzkyXkEyXkFqcGdeQXVyNTgyNTA4MjM@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=8ykEy-yPBFc',
        created_by: 'Hayao Miyazaki',
        year_of_publication: '1986',
        length: '1 hour : 42 minutes',
        allowed_age: '13+',
        genre_name: 'ANIME',
        genreId: animeGenreId,
        typeId: movieTypeId
    },
    {
        title: 'My Neighbor Totoro',
        description: 'When two young girls move to the countryside, they discover the magical and profoundly mysterious Totoro, a giant creature that only the youngest girl, Satsuki, can see.',
        slug: 'my-neighbor-totoro',
        image: 'https://m.media-amazon.com/images/M/MV5BMjg3ZmIyYWMtYmRmMC00YTcyLTgzMjItODk3Yjc4ZDc5ODE5XkEyXkFqcGdeQXVyMTYzMDM0NTU@._V1_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=92a7Hj0ijLs',
        created_by: 'Hayao Miyazaki',
        year_of_publication: '1988',
        length: '1 hour : 49 minutes',
        allowed_age: '13+',
        genre_name: 'ANIME',
        genreId: animeGenreId,
        typeId: movieTypeId
    },
    {
        title: 'Ghost in the Shell',
        description: 'In the year 2020, a terrorist attack led by the "Ghost in the Shell" organization triggers a major security crisis. The members of Public Security Section 9 are recruited to track down the mysterious group and its leader, Motoko Kusanagi.',
        slug: 'ghost-in-the-shell',
        image: 'https://m.media-amazon.com/images/M/MV5BOTFjMzg5MGQtNDg0NC00ZTJjLWFhYmQtYzY0M2YzZDVjOTUxL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=b5g1xubyuVs',
        created_by: 'Mamoru Oshii',
        year_of_publication: '1995',
        length: '1 hour : 55 minutes',
        allowed_age: '13+',
        genre_name: 'ANIME',
        genreId: animeGenreId,
        typeId: movieTypeId
    }, 
    {
        title: 'The Raid: Redemption',
        description: 'A SWAT team becomes trapped inside a building full of killers with no backup, and they must fight or die.',
        slug: 'the-raid-redemption',
        image: 'https://m.media-amazon.com/images/M/MV5BY2UyNDM1ZmUtM2E4Mi00ZDEzLWFhMTEtOGVlYjQ2NDZiYjg3XkEyXkFqcGdeQXVyNzI1NzMxNzM@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=m6Q7KnXpNOg',
        created_by: 'Gareth Evans',
        year_of_publication: '2011',
        length: '1 hour : 57 minutes',
        allowed_age: '17+',
        genre_name: 'ACTION',
        genreId: actionGenreId,
        typeId: movieTypeId
    }, 
    {
        title: 'NCIS',
        description: 'The cases of the Naval Criminal Investigative Service\'s Washington, D.C. Major Case Response Team.',
        slug: 'ncis',
        image: 'https://m.media-amazon.com/images/M/MV5BYjVlMjZhYzYtOGQxNC00OTQxLTk2NzEtMWFmMmNhODA4YjYzXkEyXkFqcGdeQXVyNjQ3MDgwNjY@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=LluQHGxXGdw',
        created_by: 'Donald P. Bellisario, Don McGill, Gary Glasberg',
        year_of_publication: '2003',
        length: '18 seasons : 433 episodes',
        allowed_age: '17+',
        genre_name: 'ACTION',
        genreId: actionGenreId,
        typeId: serieTypeId
    },
    {
        title: 'The Rookie',
        description: 'Starting over isn\'t easy, especially for John Nolan who, after a life-altering incident, is pursuing his dream of joining the LAPD.',
        slug: 'the-rookie',
        image: 'https://m.media-amazon.com/images/M/MV5BOTY5OWFmMzAtZTIxYi00NGM4LTk3YWMtY2MyYzMwOWVhZWM0XkEyXkFqcGdeQXVyMzAzNTY3MDM@._V1_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=_HgC1TN8FVk',
        created_by: 'Alexi Hawley',
        year_of_publication: '2018',
        length: '4 seasons : 72 episodes',
        allowed_age: '17+',
        genre_name: 'ACTION',
        genreId: actionGenreId,
        typeId: serieTypeId
    },
    {
        title: 'The Mandalorian',
        description: 'The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.',
        slug: 'the-mandalorian',
        image: 'https://m.media-amazon.com/images/M/MV5BN2M5YWFjN2YtYzU2YS00NzBlLTgwZWUtYWQzNWFhNDkyYjg3XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=aOC8E8z_ifw',
        created_by: 'Jon Favreau',
        year_of_publication: '2019',
        length: '3 seasons : 25 episodes',
        allowed_age: '17+',
        genre_name: 'ACTION',
        genreId: actionGenreId,
        typeId: serieTypeId
    },
    {
        title: 'Chicago Fire',
        description: 'The story of firefighters and paramedics in the city of Chicago, both on a personal and professional level.',
        slug: 'chicago-fire',
        image: 'https://m.media-amazon.com/images/M/MV5BOWZlZDZhYTQtMjJiMy00MTliLWIwYTMtMWZlOGQ1ZGE5ZGUxXkEyXkFqcGdeQXVyMTUwMzM5ODkz._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=IIeSDILTE5M',
        created_by: 'Michael Brandt, Derek Haas, Chris Kramp',
        year_of_publication: '2012',
        length: '10 seasons : 200 episodes',
        allowed_age: '17+',
        genre_name: 'ACTION',
        genreId: actionGenreId,
        typeId: serieTypeId
    }, 
    {
        title: 'The Boys',
        description: 'A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.',
        slug: 'the-boys',
        image: 'https://m.media-amazon.com/images/M/MV5BOTEyNDJhMDAtY2U5ZS00OTMzLTkwODktMjU3MjFkZWVlMGYyXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=M1bhOaLV4FU',
        created_by: 'Seth Rogen, Evan Goldberg',
        year_of_publication: '2019',
        length: '3 seasons : 32 episodes',
        allowed_age: '17+',
        genre_name: 'ACTION',
        genreId: actionGenreId,
        typeId: serieTypeId
    },
    {
        title: 'The Departed',
        description: 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.',
        slug: 'the-departed',
        image: 'https://m.media-amazon.com/images/M/MV5BNDUxMzk3ZTAtNGYwZi00ZjI1LTllMmItMGY2OWI4YTMzM2I3XkEyXkFqcGdeQXVyMjQ0NzE0MQ@@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=iojhqm0JTW4',
        created_by: 'Martin Scorsese',
        year_of_publication: '2006',
        length: '1 hour : 53 minutes',
        allowed_age: '18+',
        genre_name: 'CRIME',
        genreId: crimeGenreId,
        typeId: movieTypeId
    },
    {
        title: 'Law & Order: Special Victims Unit',
        description: 'This series follows the Special Victims Unit, a specially trained squad of detectives in the New York City Police Department that investigate sexually related crimes.',
        slug: 'law-and-order-special-victims-unit',
        image: 'https://m.media-amazon.com/images/M/MV5BYjM5OTY1OGEtODI3YS00NGY4LWFmNzAtZGY1OGYzMjU4NzExXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=O53wYUc_fA4',
        created_by: 'Dick Wolf',
        year_of_publication: '1999',
        length: '22 seasons : 598 episodes',
        allowed_age: '17+',
        genre_name: 'CRIME',
        genreId: crimeGenreId,
        typeId: serieTypeId
    },
    {
        title: 'Criminal Minds',
        description: 'A group of criminal profilers who work for the FBI as members of its Behavioral Analysis Unit (BAU) using behavioral analysis and profiling to help investigate crimes and find the suspect known as the unsub.',
        slug: 'criminal-minds',
        image: 'https://m.media-amazon.com/images/M/MV5BNGE2ZmFkZTYtNjRiOS00ZjE3LThjOWMtZTViZjRmNDFjNTQwXkEyXkFqcGdeQXVyNjg4NzAyOTA@._V1_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=NTYxiJBbEZk',
        created_by: 'Jeff Davis',
        year_of_publication: '2005',
        length: '15 seasons : 300 episodes',
        allowed_age: '17+',
        genre_name: 'CRIME',
        genreId: crimeGenreId,
        typeId: serieTypeId
    },
    {
        title: 'The Wire',
        description: 'The Baltimore drug scene, as seen through the eyes of drug dealers and law enforcement.',
        slug: 'the-wire',
        image: 'https://m.media-amazon.com/images/M/MV5BZmY5ZDMxODEtNWIwOS00NjdkLTkyMjktNWRjMDhmYjJjN2RmXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=1S5khOZ1wBs',
        created_by: 'David Simon',
        year_of_publication: '2002',
        length: '5 seasons : 60 episodes',
        allowed_age: '17+',
        genre_name: 'CRIME',
        genreId: crimeGenreId,
        typeId: serieTypeId
    },
    {
        title: 'Castle',
        description: 'A suave, best-selling author teams up with a strait-laced detective to solve crimes in New York City.',
        slug: 'castle',
        image: 'https://m.media-amazon.com/images/M/MV5BMjM2NjU0ODU0NF5BMl5BanBnXkFtZTgwMDAwMzg5NjE@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=xjrObBtzGYg',
        created_by: 'Alexi Hawley',
        year_of_publication: '2009',
        length: '8 seasons : 158 episodes',
        allowed_age: '17+',
        genre_name: 'CRIME',
        genreId: crimeGenreId,
        typeId: serieTypeId
    },
    {
        title: 'The Walking Dead',
        description: 'Sheriff Deputy Rick Grimes wakes up from a coma to learn the world is in a post-apocalyptic flesh-eating zombie epidemic.',
        slug: 'the-walking-dead',
        image: 'https://m.media-amazon.com/images/M/MV5BOTUwODI0ODE3OF5BMl5BanBnXkFtZTcwNjQ3NTM0OA@@._V1_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=sfAc2U20uyg',
        created_by: 'Frank Darabont, Tony Moore, Robert Kirkman',
        year_of_publication: '2010',
        length: '11 seasons : 117 episodes',
        allowed_age: '17+',
        genre_name: 'ADVENTURE',
        genreId: adventureGenreId,
        typeId: serieTypeId
    },
    {
        title: 'Lost',
        description: 'The survivors of a plane crash are forced to work together in order to survive on a seemingly deserted tropical island.',
        slug: 'lost',
        image: 'https://m.media-amazon.com/images/M/MV5BNzhlY2E5NDUtYjJjYy00ODg3LWFkZWQtYTVmMzU4ZWZmOWJkXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=KTu8iDynwNc',
        created_by: 'J.J. Abrams, Damon Lindelof',
        year_of_publication: '2004',
        length: '6 seasons : 121 episodes',
        allowed_age: '17+',
        genre_name: 'ADVENTURE',
        genreId: adventureGenreId,
        typeId: serieTypeId
    },
    {
        title: 'Vikings',
        description: 'A history-based drama series that tells the story of Ragnar Lothbrok, a legendary Viking warrior, and his crew of brave warriors who travel across the oceans.',
        slug: 'vikings',
        image: 'https://m.media-amazon.com/images/M/MV5BODk4ZjU0NDUtYjdlOS00OTljLTgwZTUtYjkyZjk1NzExZGIzXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=9GgxinPwAGc',
        created_by: 'Michael Hirst',
        year_of_publication: '2013',
        length: '6 seasons : 73 episodes',
        allowed_age: '17+',
        genre_name: 'ADVENTURE',
        genreId: adventureGenreId,
        typeId: serieTypeId
    },
    {
        title: 'Outlander',
        description: 'A nurse from World War II is mistakenly swept back to the year 1743 in the Scottish Highlands, and falls in love with a chieftain of Clan Fraser.',
        slug: 'outlander',
        image: 'https://m.media-amazon.com/images/M/MV5BNGY5NmFmOGItYTY4My00M2JlLTkzYTMtZTUzN2YyZmUzMTlmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=PFFKjptRr7Y',
        created_by: 'Graham Brown, Ronald D. Moore',
        year_of_publication: '2014',
        length: '6 seasons : 64 episodes',
        allowed_age: '17+',
        genre_name: 'ADVENTURE',
        genreId: adventureGenreId,
        typeId: serieTypeId
    },
    {
        title: 'Stargate SG-1',
        description: 'A secret military team, SG-1, is formed to explore other planets through the recently discovered Stargates.',
        slug: 'stargate-sg-1',
        image: 'https://m.media-amazon.com/images/M/MV5BMTc3MjEwMTc5N15BMl5BanBnXkFtZTcwNzQ2NjQ4NA@@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=bS-4JP9w49Q',
        created_by: 'Brad Wright, Jonathan Glassner, Brad Abrams',
        year_of_publication: '1997',
        length: '10 seasons : 231 episodes',
        allowed_age: '17+',
        genre_name: 'ADVENTURE',
        genreId: adventureGenreId,
        typeId: serieTypeId
    },
    {
        title: 'The Motorcycle Diaries',
        description: 'The autobiographical adventure film follows the journey of two friends and their discovery of the difference in society, action with one community having everything while the other has to struggle for nothing.',
        slug: 'the-motorcycle-diaries',
        image: 'https://m.media-amazon.com/images/M/MV5BOTNmZTgyMzAtMTUwZC00NjAwLTk4MjktODllYTY5YTUwN2YwXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=RWBsQArUkQY',
        created_by: 'Walter Salles, Andru Wang',
        year_of_publication: '2004',
        length: '1 hour : 48 minutes',
        allowed_age: '17+',
        genre_name: 'ADVENTURE',
        genreId: adventureGenreId,
        typeId: movieTypeId
    },
    {
        title: 'The Great Alaskan Race',
        description: 'The adventure film follows Leonhard, a sweepstakes race winner whose life changes after the death of his wife. Leonhard lives with his daughter in Nome, where a pandemic starts when children start of Nome start coughing, and the illness is recognized to be Diphtheria by doctor Welch.',
        slug: 'the-great-alaskan-race',
        image: 'https://m.media-amazon.com/images/M/MV5BNzY2NDFhYzctM2ZmMi00MmU3LWJkOWMtM2UyYzQzYzZmYjQzXkEyXkFqcGdeQXVyMTA0NTU3MDYz._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=q8gWaE2majI',
        created_by: 'Rob Nilsson',
        year_of_publication: '1983',
        length: '1 hour : 40 minutes',
        allowed_age: '17+',
        genre_name: 'ADVENTURE',
        genreId: adventureGenreId,
        typeId: movieTypeId
    },
    {
        title: 'Brave',
        description: 'Determined to make her own path in life, Princess Merida defies a custom that brings chaos to her kingdom. Granted one wish, Merida must rely on her bravery and her archery skills to undo a beastly curse.',
        slug: 'brave',
        image: 'https://m.media-amazon.com/images/M/MV5BMzgwODk3ODA1NF5BMl5BanBnXkFtZTcwNjU3NjQ0Nw@@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=TEHWDA_6e3M',
        created_by: 'Mark Andrews, Brenda Chapman',
        year_of_publication: '2012',
        length: '1 hour : 42 minutes',
        allowed_age: '13+',
        genre_name: 'ADVENTURE',
        genreId: adventureGenreId,
        typeId: movieTypeId
    },
    {
        title: 'Dungeons & Dragons: Honor Among Thieves',
        description: 'A charming thief assembles a ragtag group of adventurers to steal a powerful relic, but their heist goes awry when they cross the wrong people and are forced to go on an epic quest to make things right.',
        slug: 'dungeons-and-dragons-honor-among-thieves',
        image: 'https://img.rgstatic.com/content/movie/f94ee5df-c7f9-4780-b532-05684cd56bfa/poster-780.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=IiMinixSXII',
        created_by: 'Jonathan M. Goldstein, John Francis Daley',
        year_of_publication: '2023',
        length: '1 hour : 52 minutes',
        allowed_age: '17+',
        genre_name: 'NEW',
        genreId: newGenreId,
        typeId: movieTypeId
    },
    {
        title: 'Teenage Mutant Ninja Turtles: Mutant Mayhem',
        description: 'The adventures of the Teenage Mutant Ninja Turtles continue as they face a new threat that puts them all in danger.',
        slug: 'teenage-mutant-ninja-turtles-mutant-mayhem',
        image: 'https://m.media-amazon.com/images/M/MV5BYzE4MTllZTktMTIyZS00Yzg1LTg1YzAtMWQwZTZkNjNkODNjXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=IHvzw4Ibuho',
        created_by: 'Jonathan Liebesman',
        year_of_publication: '2023',
        length: '1 hour : 52 minutes',
        allowed_age: '13+',
        genre_name: 'NEW',
        genreId: newGenreId,
        typeId: movieTypeId
    },
    {
        title: 'Blue Beetle',
        description: 'The story of Jaime Reyes, a young man who gains the powers of a scarab and becomes the superhero known as Blue Beetle.',
        slug: 'blue-beetle',
        image: 'https://m.media-amazon.com/images/M/MV5BMmY1ODUzZGItNDllOS00MDBhLTg4NmUtYjU4YjUxMGNlYmMwXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=UljKRKmfdkw',
        created_by: 'Jaume Collet-Serra',
        year_of_publication: '2023',
        length: '1 hour : 52 minutes',
        allowed_age: '17+',
        genre_name: 'NEW',
        genreId: newGenreId,
        typeId: movieTypeId
    }, 
    {
        title: 'The Other Black Girl',
        description: 'An African-American editorial assistant works at a white NYC publishing firm. When a black co-worker arrives she gets excited, but is the new girl a friend or a foe?',
        slug: 'the-other-black-girl',
        image: 'https://m.media-amazon.com/images/M/MV5BMGNiODM0NzktZjA5Zi00NWQ3LTljZGMtNDAwNGJhYThmNDYxXkEyXkFqcGdeQXVyMTM1NjM2ODg1._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=7gmYkNE0wYw',
        created_by: 'Ayanna A. Floyd',
        year_of_publication: '2023',
        length: '1 season : 8 episodes',
        allowed_age: '17+',
        genre_name: 'NEW',
        genreId: newGenreId,
        typeId: serieTypeId
    },
    {
        title: 'Percy Jackson and the Olympians',
        description: 'Demigod Percy Jackson leads a quest across America to prevent a war among the Olympian gods.',
        slug: 'percy-jackson-and-the-olympians',
        image: 'https://m.media-amazon.com/images/M/MV5BMTQ5NDlmZWUtMjIyMC00NzQ3LTg3OWYtMzRkY2FiNzQ0Njc4XkEyXkFqcGdeQXVyNDQ2MTMzODA@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=bzHMAXqFFvc&t=19s',
        created_by: 'Walker Scobell, Leah Jeffries, Aryan Simhadri, Jason Mantzoukas',
        year_of_publication: '2023',
        length: '1 season : 10 episodes',
        allowed_age: '17+',
        genre_name: 'NEW',
        genreId: newGenreId,
        typeId: serieTypeId
    },
    {
        title: 'The Diplomat',
        description: 'In the midst of an international crisis, Kate Wyler, a career diplomat, lands in a high-profile job for which she is not suited, with tectonic implications for her marriage and her political future.',
        slug: 'the-diplomat',
        image: 'https://m.media-amazon.com/images/M/MV5BM2Y5YTFjMjEtM2Q0OS00NzhlLWFmYjQtZjczYzQ2NDI0NTRjXkEyXkFqcGdeQXVyNTE1NjY5Mg@@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=lV6sJlBbhPs',
        created_by: 'TBA',
        year_of_publication: '2023',
        length: '1 season : 10 episodes',
        allowed_age: '17+',
        genre_name: 'NEW',
        genreId: newGenreId,
        typeId: serieTypeId
    },
    {
        title: 'Lessons in Chemistry',
        description: 'Set in the early 1960s, Elizabeth Zott\'s dream of being a chemist is put on hold when she finds herself pregnant, alone, and fired from her lab.',
        slug: 'lessons-in-chemistry',
        image: 'https://m.media-amazon.com/images/M/MV5BNzM5ODUwOGMtNDFjNi00OTI1LWIzMmYtMWM4MWRhZjg4NGVjXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=-1PuK8mxASE',
        created_by: 'Brie Larson, Stephanie Koenig, Alice Halsey, Joy Jacobson',
        year_of_publication: '2023',
        length: '1 season : 10 episodes',
        allowed_age: '17+',
        genre_name: 'NEW',
        genreId: newGenreId,
        typeId: serieTypeId
    },
    {
        title: 'Still Up',
        description: 'An impulsive and free-spirited aspiring illustrator whose questions over her daughter\'s future start keeping her up at night, and the socially anxious yet gifted journalist Danny.',
        slug: 'still-up',
        image: 'https://m.media-amazon.com/images/M/MV5BYTNmOWI3ODktZjAyNC00MmE5LWE5ZWEtMzZjY2EzOTBiMzM3XkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=3InTFGgHT14',
        created_by: 'Antonia Thomas, Craig Roberts, Blake Harrison, Rich Fulcher',
        year_of_publication: '2023',
        length: '1 season : 10 episodes',
        allowed_age: '17+',
        genre_name: 'NEW',
        genreId: newGenreId,
        typeId: serieTypeId
    },
    {
        title: 'The Creator',
        description: 'Against the backdrop of a war between humans and robots with artificial intelligence, a former soldier finds the secret weapon, a robot in the form of a young child.',
        slug: 'the-creator',
        image: 'https://m.media-amazon.com/images/M/MV5BNDUyNTIzNDQtYTZmMi00M2FlLTgyZjUtYWViZWNhMDYzMjE4XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=ex3C1-5Dhb8',
        created_by: 'Gareth Edwards',
        year_of_publication: '2023',
        length: '1 hour : 52 minutes',
        allowed_age: '17+',
        genre_name: 'FAMILY',
        genreId: familyGenreId,
        typeId: movieTypeId
    },
    {
        title: 'Barbie',
        description: 'Barbie suffers a crisis that leads her to question her world and her existence.',
        slug: 'barbie',
        image: 'https://m.media-amazon.com/images/M/MV5BNjU3N2QxNzYtMjk1NC00MTc4LTk1NTQtMmUxNTljM2I0NDA5XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=pBk4NYhWNMM',
        created_by: 'Greta Gerwig',
        year_of_publication: '2023',
        length: '1 hour : 52 minutes',
        allowed_age: '17+',
        genre_name: 'FAMILY',
        genreId: familyGenreId,
        typeId: movieTypeId
    },
    {
        title: 'Oppenheimer',
        description: 'The story of American scientist, J. Robert Oppenheimer, and his role in the development of the atomic bomb.',
        slug: 'oppenheimer',
        image: 'https://m.media-amazon.com/images/M/MV5BMDEzNDdjYTctNjA4ZS00ZDgzLTkxNmUtMTQwMzUyMmFhMWRhXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=94U5MEJQMBY',
        created_by: 'Christopher Nolan',
        year_of_publication: '2023',
        length: '1 hour : 52 minutes',
        allowed_age: '17+',
        genre_name: 'FAMILY',
        genreId: familyGenreId,
        typeId: movieTypeId
    },
    {
        title: 'Wish',
        description: 'Wish will follow a young girl named Asha who wishes on a star and gets a more direct answer than she bargained for when a trouble-making star comes down from the sky to join her.',
        slug: 'wish',
        image: 'https://m.media-amazon.com/images/M/MV5BYWQ4M2ZmODItNzZhYi00MzY1LTk2ZmItYTUwODI2NzJmN2JiXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=oyRxxpD3yNw',
        created_by: 'Chris Buck, Fawn Veerasunthorn',
        year_of_publication: '2023',
        length: '1 hour : 52 minutes',
        allowed_age: '17+',
        genre_name: 'FAMILY',
        genreId: familyGenreId,
        typeId: movieTypeId
    },
    {
        title: 'Gamera: Rebirth',
        description: 'The series continues the adventures of Gamera, a giant, fire-breathing turtle who protects the Earth from giant monsters.',
        slug: 'gamera-rebirth',
        image: 'https://m.media-amazon.com/images/M/MV5BZTM3MDNlNDEtNTMzYS00NGQ3LWJmY2MtNTI5ZjUzMjY0ZDgzXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=Fzg9xm8Ow9Q',
        created_by: 'TBA',
        year_of_publication: '2023',
        length: '1 season : 10 episodes',
        allowed_age: '16+',
        genre_name: 'FAMILY',
        genreId: familyGenreId,
        typeId: serieTypeId
    },
    {
        title: 'Oddballs',
        description: 'A group of teenagers with unique abilities who are training to become heroes and protect the world.',
        slug: 'oddballs',
        image: 'https://m.media-amazon.com/images/M/MV5BZDQ0OWVjZTctM2I3NC00ZTliLWI5NTItMjYwNTM5MmVmYzU3XkEyXkFqcGdeQXVyNzEwMzUxMzU@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=aeMDgX9jga4',
        created_by: 'TBA',
        year_of_publication: '2023',
        length: '1 season : 10 episodes',
        allowed_age: '12+',
        genre_name: 'FAMILY',
        genreId: familyGenreId,
        typeId: serieTypeId
    },
    {
        title: 'The Waltons',
        description: 'The life and trials of a 1930s and 1940s Virginia mountain family through financial depression and World War II.',
        slug: 'the-waltons',
        image: 'https://m.media-amazon.com/images/M/MV5BMjc1MmI0MGItZWZkMi00M2E0LWJjMWMtMjg0YmNlMmEyZjY0XkEyXkFqcGdeQXVyMjAwNzczNTU@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=qpmRcP8S7Bo',
        created_by: 'TBA',
        year_of_publication: '1972',
        length: '10 seasons : 114 episodes',
        allowed_age: '12+',
        genre_name: 'FAMILY',
        genreId: familyGenreId,
        typeId: serieTypeId
    },
    {
        title: 'Zoey 101',
        description: 'Zoey Brooks and her brother, Dustin, attend their first day at Pacific Coast Academy, a private boarding school that enrolls girls for the first time in its history.',
        slug: 'zoey-101',
        image: 'https://m.media-amazon.com/images/M/MV5BNzMyMDM3MTY1M15BMl5BanBnXkFtZTgwMjQxNDIzMTE@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=2a3VKZyu_0g',
        created_by: 'TBA',
        year_of_publication: '2005',
        length: '4 seasons : 64 episodes',
        allowed_age: '12+',
        genre_name: 'FAMILY',
        genreId: familyGenreId,
        typeId: serieTypeId
    },
    {
        title: 'Jessie',
        description: 'A Texan teen moves to New York City to follow her dreams and ends up as a nanny for a high-profile couple\'s four children.',
        slug: 'jessie',
        image: 'https://m.media-amazon.com/images/M/MV5BMTY0MTYyNTk5M15BMl5BanBnXkFtZTgwMjE0ODYzMjE@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=AawTMmg7ohg',
        created_by: 'TBA',
        year_of_publication: '2011',
        length: '4 seasons : 40 episodes',
        allowed_age: '12+',
        genre_name: 'FAMILY',
        genreId: familyGenreId,
        typeId: serieTypeId
    },
    {
        title: 'It Lives Inside',
        description: 'An Indian-American teenager struggling with her cultural identity has a falling out with her former best friend and, in the process, unwittingly releases a demonic entity that grows stronger by feeding on her loneliness.',
        slug: 'it-lives-inside',
        image: 'https://m.media-amazon.com/images/M/MV5BMDIyMzRjZjktZGJhMC00MDczLWI5OTQtZmU4MzkwNDBkZmFmXkEyXkFqcGdeQXVyMTMzOTQyOTk1._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=a5xUbuYHdi8',
        created_by: 'Bishal Dutta',
        year_of_publication: '2023',
        length: '1 hour : 52 minutes',
        allowed_age: '17+',
        genre_name: 'HORROR',
        genreId: horrorGenreId,
        typeId: movieTypeId
    },
    {
        title: 'Cobweb',
        description: 'An eight-year-old boy tries to investigate the mysterious knocking sounds that are coming from inside the walls of his house, unveiling a dark secret that his sinister parents have kept hidden from him.',
        slug: 'cobweb',
        image: 'https://m.media-amazon.com/images/M/MV5BMWI2NjQ2NGYtNDMwYS00YzNlLWFjZTctNzQ5MTRiYzQyZjMzXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=GMBpu1L9JuU',
        created_by: 'Samuel Bodin',
        year_of_publication: '2023',
        length: '1 hour : 52 minutes',
        allowed_age: '17+',
        genre_name: 'HORROR',
        genreId: horrorGenreId,
        typeId: movieTypeId
    },
    {
        title: 'Totally Killer',
        description: 'When the infamous "Sweet Sixteen Killer" returns 35 years after his first murder spree to claim another victim, 17-year-old Jamie accidentally travels back in time to 1987, determined to stop the killer before he can start.',
        slug: 'totally-killer',
        image: 'https://m.media-amazon.com/images/M/MV5BYzQwYzY4YWUtNDMxMS00Y2UxLTlhODQtY2ExZDY5ZDhhZGMzXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=vNm3VPPKEQI',
        created_by: 'Nahnatchka Khan',
        year_of_publication: '2023',
        length: '1 hour : 52 minutes',
        allowed_age: '17+',
        genre_name: 'HORROR',
        genreId: horrorGenreId,
        typeId: movieTypeId
    },
    {
        title: 'Borderland',
        description: 'Part of the After Dark horror craze of the 2000s, Borderland told the true story of American tourists who fall prey to the narco-satanists who were under a cult influence.',
        slug: 'borderland',
        image: 'https://m.media-amazon.com/images/M/MV5BMjAyNjY0NDI3N15BMl5BanBnXkFtZTcwOTg4OTQ0MQ@@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=ivjwqI8t6Zk',
        created_by: 'TBA',
        year_of_publication: '2007',
        length: '1 hour : 52 minutes',
        allowed_age: '17+',
        genre_name: 'HORROR',
        genreId: horrorGenreId,
        typeId: movieTypeId
    },
    {
        title: 'Rogue',
        description: 'An American journalist on assignment in the Australian outback encounters a man-eating crocodile while trapped on a rapidly flooding mud island.',
        slug: 'rogue',
        image: 'https://m.media-amazon.com/images/M/MV5BMTYxNzAxNDU3Ml5BMl5BanBnXkFtZTcwMDU0ODg2MQ@@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=a5wbVAkBZIM',
        created_by: 'Greg McLean',
        year_of_publication: '2007',
        length: '1 hour : 52 minutes',
        allowed_age: '17+',
        genre_name: 'HORROR',
        genreId: horrorGenreId,
        typeId: movieTypeId
    },
    {
        title: 'The Girl Next Door',
        description: 'Follows the unspeakable torture and abuses committed on a teenage girl in the care of her aunt and the boys who witness and fail to report the crime.',
        slug: 'the-girl-next-door',
        image: 'https://m.media-amazon.com/images/M/MV5BMTUwMDcyNjE1MF5BMl5BanBnXkFtZTcwOTA1Njg0MQ@@._V1_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=F9p_zENS4EA',
        created_by: 'Gregory Wilson',
        year_of_publication: '2007',
        length: '1 season : 10 episodes',
        allowed_age: '17+',
        genre_name: 'HORROR',
        genreId: horrorGenreId,
        typeId: serieTypeId
    },
    {
        title: 'The Exorcist',
        description: 'The series follows the experiences of two young girls who become possessed by malevolent entities, leading their parents to seek help from two priests who specialize in battling such evil forces.',
        slug: 'the-exorcist',
        image: 'https://m.media-amazon.com/images/M/MV5BYWFlZGY2NDktY2ZjOS00ZWNkLTg0ZDAtZDY4MTM1ODU4ZjljXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=PIxpPMyGcpU',
        created_by: 'William Peter Blatty',
        year_of_publication: '1973',
        length: '1 season : 10 episodes',
        allowed_age: '17+',
        genre_name: 'HORROR',
        genreId: horrorGenreId,
        typeId: serieTypeId
    },
    {
        title: 'American Horror Story',
        description: 'An anthology series that presents different themes and characters in each season, including horror, fantasy, and science fiction elements.',
        slug: 'american-horror-story',
        image: 'https://m.media-amazon.com/images/M/MV5BNjIzMjM2ZWMtNGE0Mi00NzY3LTllOWEtZGFhNTUyOTlkZWZlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=4qniWD7bFu0',
        created_by: 'Ryan Murphy',
        year_of_publication: '2011',
        length: '10 seasons : 112 episodes',
        allowed_age: '17+',
        genre_name: 'HORROR',
        genreId: horrorGenreId,
        typeId: serieTypeId
    },
    {
        title: 'Zodiac',
        description: 'A group of journalists at San Francisco Chronicle who investigate a series of murders after receiving encrypted letters purporting to be from the killer.',
        slug: 'zodiac',
        image: 'https://m.media-amazon.com/images/M/MV5BN2UwNDc5NmEtNjVjZS00OTI5LWE5YjctMWM3ZjBiZGYwMGI2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=yNncHPl1UXg',
        created_by: 'David Fincher',
        year_of_publication: '2007',
        length: '1 season : 10 episodes',
        allowed_age: '17+',
        genre_name: 'HORROR',
        genreId: horrorGenreId,
        typeId: serieTypeId
    },
    {
        title: 'Devil\'s Knot',
        description: 'A group of teenage boys were allegedly inspired to carry out satanic rituals, which allegedly resulted in the deaths of three eight-year old boys.',
        slug: 'devils-knot',
        image: 'https://m.media-amazon.com/images/M/MV5BMjI2NzE3NTU1NF5BMl5BanBnXkFtZTgwNDAyMTkzMTE@._V1_FMjpg_UX1000_.jpg',
        youtubeURL: 'https://www.youtube.com/watch?v=lLG_RokHHRI',
        created_by: 'TBA',
        year_of_publication: '2014',
        length: '1 season : 10 episodes',
        allowed_age: '17+',
        genre_name: 'HORROR',
        genreId: horrorGenreId,
        typeId: serieTypeId
    }
    ]
   })

   await prisma.$disconnect();

	return res.json('Hello - data created :)');
};

export default handler;
